defaults:
  - log: exp_logger # 用于实验参数记录，集成到tensorboard comet等
  - log: hypra_logger # hypra集成的python logger配置
data:
  path: "/home/chenc/PycharmProjects/pytorch-lighting-template"
  train_manifest: "/mnt/workspace/datasets/libri/train_clean_100.json"
  val_manifest: "/mnt/workspace/datasets/libri/dev_clean.json"
  labels: [" ","'","a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
           "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
train:
  total_epoch: 100
  checkpoint: null # None或模型文件的位置
  gpus: 1
  tpu_core_num: null
  train_batch_size: 16
  dev_batch_size: 32
  learning_rate: 1e-1
  weight_decay: 1e-4
  amp_level: "O2"
  precision: 32
  amp_backend: native
  accelerator: ddp
